spring:
  application:
    name: collector
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
  config:
    import: "configserver:"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
server:
  port: 0