spring:
  application:
    name: collector
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  config:
    import: configserver:http://localhost:8888