aggregator:
  kafka:
    consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: telemetry.aggregator
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserialization.SensorEventDeserializer
        enable.auto.commit: false
      topics:
        sensors-events: telemetry.sensors.v1
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: telemetry.aggregator
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serialization.GeneralAvroSerializer
      topics:
        snapshots-events: telemetry.snapshots.v1
server:
  port: 8090