analyzer:
  kafka:
    hubConsumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: telemetry.analyzer.hubs
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserialization.HubEventDeserializer
        enable.auto.commit: false
      topics:
        hubs-events: telemetry.hubs.v1
    snapshotConsumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: telemetry.analyzer.snapshots
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserialization.SensorsSnapshotDeserializer
        enable.auto.commit: false
      topics:
        snapshots-events: telemetry.snapshots.v1
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/analyzer-db
    username: analyzer
    password: analyzer